# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72ab288f3b2eec3387b4d7123718fa49ebb189219910013608d4ed5baf779b410e5aa8cd37fc51361ebfdd3ee51b7bd23b628c7321f5cd4cce3377cf81572ae3

test:
  secret_key_base: d969539c4eb3212fdd7b9e24fbaacb40c1f7c39e21a172d49c25b0b9fc718693cf900c220096ebd77acabee654e5618b599a4b882972fe7a1de55fe7a0f843aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
